In [1]:
import numpy as np

In [2]:
np.ones((3,5),dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [3]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

**Array Özellikleri**

* ndim: boyut sayısı
* shape: boyut bilgisi
* size : toplam eleman sayısı
* dtype : array veri tipi 

In [4]:
a= np.random.randint(10, size=10)

In [5]:
a.ndim   #tek boyutlu dizi

1

In [6]:
a.shape

(10,)

In [7]:
a.size

10

In [8]:
a.dtype

dtype('int32')

In [9]:
b = np.random.randint(10, size=(3,5))

In [10]:
b

array([[2, 8, 1, 9, 9],
       [5, 6, 8, 4, 9],
       [2, 1, 0, 9, 8]])

In [11]:
b.ndim

2

In [12]:
b.shape

(3, 5)

**Yeniden Şekillendirme (reshaping)**

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Birleştirme**

In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [16]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [17]:
z = np.array([7,8,9])

In [18]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#iki boyut

In [20]:
a= np.array([[1,2,3],
            [4,5,6]])

In [21]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
np.concatenate([a,a] , axis=1)  #sütun bazında bırlestırme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Array Ayırma**

In [23]:
x = np.array([1,2,3,99,99,3,2,1])

In [24]:
a,b,c =np.split(x,[3,5])

In [25]:
a

array([1, 2, 3])

In [26]:
b

array([99, 99])

In [27]:
c

array([3, 2, 1])

In [28]:
#iki boyutlu ayırma

In [29]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
ust,alt = np.vsplit(m,[2])

In [31]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
sag,sol=np.hsplit(m,[2])

In [36]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [37]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Array Sıralama(Sorting)**

In [38]:
v= np.array([2,1,4,3,5])

In [39]:
v

array([2, 1, 4, 3, 5])

In [40]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [41]:
v

array([2, 1, 4, 3, 5])

In [42]:
v.sort()

In [43]:
v

array([1, 2, 3, 4, 5])

In [44]:
#iki boyutlu array siralama

In [45]:
m = np.random.normal(30,5, (3,3))

In [46]:
m

array([[26.29227051, 37.47667903, 35.07037399],
       [27.40578372, 25.57365445, 21.10453012],
       [33.47150533, 29.47952666, 22.39369449]])

In [50]:
np.sort(m, axis=1)    #yatayda (satirlara gore) siralama yapti

array([[26.29227051, 35.07037399, 37.47667903],
       [21.10453012, 25.57365445, 27.40578372],
       [22.39369449, 29.47952666, 33.47150533]])

In [51]:
np.sort(m, axis=0)    #dikeyde (sutunlara gore) siralama yapti

array([[26.29227051, 25.57365445, 21.10453012],
       [27.40578372, 29.47952666, 22.39369449],
       [33.47150533, 37.47667903, 35.07037399]])

**Index ile elemanlara erismek**

In [52]:
a = np.random.randint(10,size=10)

In [53]:
a

array([3, 0, 7, 5, 4, 5, 2, 0, 5, 2])

In [55]:
m = np.random.randint(10,size=(3,5))
m

array([[1, 5, 9, 4, 1],
       [1, 9, 4, 6, 0],
       [6, 5, 5, 0, 2]])

In [56]:
m[0][0]

1

**Slicing**

In [57]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
a[2::3]  #ikiden baslayarak ucer ucer git

array([22, 25, 28])

In [60]:
#iki boyutlu slice islemleri

In [61]:
m = np.random.randint(10,size=(5,5))
m

array([[8, 0, 2, 5, 0],
       [5, 1, 7, 8, 5],
       [8, 3, 6, 7, 3],
       [4, 7, 4, 5, 3],
       [2, 5, 6, 4, 3]])

In [63]:
m[:,0]  #butun satirlari sec ve 0. sutun

array([8, 5, 8, 4, 2])

In [64]:
m[:,4]

array([0, 5, 3, 3, 3])

In [65]:
m[0,:]

array([8, 0, 2, 5, 0])

In [66]:
m[0:2,0:3]

array([[8, 0, 2],
       [5, 1, 7]])

In [67]:
al_getir = [1,2,3]  # fancy index

In [68]:
a[al_getir]

array([21, 22, 23])

In [69]:
#slice ile fancy
m[0:,[1,2]]

array([[0, 2],
       [1, 7],
       [3, 6],
       [7, 4],
       [5, 6]])

**Kosullu Eleman Islemleri**

In [71]:
v=np.array([1,2,3,4,5])

In [72]:
v<3

array([ True,  True, False, False, False])

In [73]:
v[v<3]

array([1, 2])

In [74]:
v*3

array([ 3,  6,  9, 12, 15])

In [75]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

**Matematiksel İslemler**

In [76]:
v=np.array([1,2,3,4,5])

In [77]:
#ufunc

In [80]:
np.subtract(v,1)  #hepsinden bir cikar

array([0, 1, 2, 3, 4])

In [81]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [82]:
np.multiply(v,3)

array([ 3,  6,  9, 12, 15])

In [83]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [85]:
np.mod(v,2)   #v%2 ile ayni sey

array([1, 0, 1, 0, 1], dtype=int32)

In [86]:
np.absolute(np.array([-3]))  #mutlak deger alma

array([3])

In [90]:
np.sin(90)

0.8939966636005579

In [89]:
np.cos(90)

-0.4480736161291701

* 5*x0 + x1 = 12
* x0 + 3*x1  = 10

In [93]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [94]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])